### ISSUE TITLE
Useless props "authenticated" in Layout components

### ISSUE THREAD

**Issue by mofas** [indiana-university/rivet-react-aspnetcore-boilerplate#5]
Hi:

When I read the source code App.js, I find it pass the "authenticated" props to Layout component.
https://github.com/indiana-university/rivet-react-aspnetcore-boilerplate/blob/master/src/Client/src/App.js

However, when I visited Layout.js 

https://github.com/indiana-university/rivet-react-aspnetcore-boilerplate/blob/master/src/Client/src/components/Layout.js

I find it doesn't use that prop, instead it read the auth status from AuthService again.
I guess the reason is that Layout component still need AuthService to get username, so it need to import AuthService anyway and also read auth status from store.

In that case, it makes "authenticated" props total useless.

**Comment by jhoerr** [comment]
Good catch, @mofas, thanks! I think it would make sense to remove that property. Please feel free to make a pull request if you're comfortable doing that.

**Comment by mofas** [comment]
Hi @jhoerr , pull request created, please help to review. Thanks.
